package com.occasi.application.exception

import org.springframework.http.HttpStatus

enum class ErrorCode(val httpStatus: HttpStatus) {
    INVALID_PHONE(HttpStatus.BAD_REQUEST),
    INVALID_OTP(HttpStatus.UNAUTHORIZED),
    OTP_EXPIRED(HttpStatus.UNAUTHORIZED),
    OTP_SEND_FAILED(HttpStatus.SERVICE_UNAVAILABLE),
    INVALID_GOOGLE_TOKEN(HttpStatus.UNAUTHORIZED),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    ARTIST_NOT_FOUND(HttpStatus.NOT_FOUND),
    DUPLICATE_ARTIST_EMAIL(HttpStatus.CONFLICT),
    INVALID_ARTIST_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    INVALID_ARTIST_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    BOOKING_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVALID_STATUS_TRANSITION(HttpStatus.BAD_REQUEST),
    PAYMENT_VERIFICATION_FAILED(HttpStatus.BAD_REQUEST),
    REFUND_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_BOOKING_REQUEST(HttpStatus.BAD_REQUEST),
    CARD_ORDER_NOT_FOUND(HttpStatus.NOT_FOUND),
    DUPLICATE_SAMPLE_ORDER(HttpStatus.CONFLICT),
    INVALID_ORDER_QUANTITY(HttpStatus.BAD_REQUEST),
    INVALID_ORDER_STATUS_TRANSITION(HttpStatus.BAD_REQUEST),
    REVIEW_NOT_ELIGIBLE(HttpStatus.FORBIDDEN),
    DUPLICATE_REVIEW(HttpStatus.CONFLICT),
    INVALID_RATING(HttpStatus.BAD_REQUEST),
    FILE_TOO_LARGE(HttpStatus.BAD_REQUEST),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    MALFORMED_REQUEST(HttpStatus.BAD_REQUEST),
    INVALID_ITEM_TYPE(HttpStatus.BAD_REQUEST),
    RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);
}
